steps:
  # Build the container image (use BUILD_ID which is always available)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cairo-cdp:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cairo-cdp:latest'
      - '.'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cairo-cdp:$BUILD_ID']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cairo-cdp:latest']

  # Decode base64 values and deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Get PROJECT_ID from gcloud config
        PROJECT_ID_VAL=$$(gcloud config get-value project 2>/dev/null)
        if [ -z "$$PROJECT_ID_VAL" ]; then
          echo "Error: Could not determine PROJECT_ID"
          exit 1
        fi
        echo "Using PROJECT_ID: $$PROJECT_ID_VAL"
        
        # Use PROJECT_NUMBER passed as substitution variable
        PROJECT_NUMBER_VAL="${_PROJECT_NUMBER}"
        if [ -z "$$PROJECT_NUMBER_VAL" ]; then
          echo "Error: PROJECT_NUMBER not provided. Pass it via _PROJECT_NUMBER substitution."
          exit 1
        fi
        echo "Using PROJECT_NUMBER: $$PROJECT_NUMBER_VAL"
        
        # Decode base64-encoded values
        ENV_VARS=$$(echo "${_ENV_VARS_B64}" | base64 -d)
        SECRETS=$$(echo "${_SECRETS_B64}" | base64 -d)
        
        # Construct service account email using project number (correct format)
        SERVICE_ACCOUNT="$$PROJECT_NUMBER_VAL-compute@developer.gserviceaccount.com"
        echo "Using Service Account: $$SERVICE_ACCOUNT"
        
        # Deploy to Cloud Run
        gcloud run deploy cairo-cdp \
          --image gcr.io/$$PROJECT_ID_VAL/cairo-cdp:latest \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances ${_INSTANCE_CONNECTION_NAME} \
          --set-env-vars "$$ENV_VARS" \
          --set-secrets "$$SECRETS" \
          --memory 2Gi \
          --cpu 2 \
          --timeout 3600 \
          --max-instances 10 \
          --min-instances 0 \
          --service-account $$SERVICE_ACCOUNT

substitutions:
  _REGION: us-central1
  _INSTANCE_CONNECTION_NAME: 'cairo-event-tracking:us-central1:cairo-db'  # Set this: PROJECT_ID:REGION:INSTANCE_NAME
  _ENV_VARS_B64: ''  # Base64-encoded environment variables (set by deploy script)
  _SECRETS_B64: ''   # Base64-encoded secrets (set by deploy script)
  _PROJECT_NUMBER: ''  # Project number (set by deploy script)

images:
  - 'gcr.io/$PROJECT_ID/cairo-cdp:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/cairo-cdp:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
